name: RSS -> Discord Webhook (DayZ)

permissions:
  contents: write

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:
    inputs:
      force_test:
        description: "Post newest item once (does not change state.json)"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RSS_URL: "https://store.steampowered.com/feeds/news/app/221100/?cc=us&l=english"
          WEBHOOK_NAME: "Būrio Ryšininkas"
          AVATAR_URL: ""
          MAX_POSTS: "3"
          POST_ON_FIRST_RUN: "0"
          FORCE_TEST: ${{ github.event.inputs.force_test == 'true' && '1' || '0' }}
          AUTHOR_NAME: "Būrio Ryšininkas"
          FOOTER_TEXT: "Kareivių Nuotykiai • DayZ naujienos"
          EMBED_COLOR: "15158332" # raudona (discord red)
          THUMBNAIL_URL: "https://cdn.discordapp.com/attachments/1458072008146288721/1458983743871123652/pranesimu_naujienos.png?ex=69619fff&is=69604e7f&hm=43ac5d5db6ad7aa3c2813e8aae78dd5dd93e41d9fe719e05d8a2b46e342bcd69&"       # jei turi DayZ logo URL, įklijuok čia
          AUTHOR_ICON_URL: ""     # jei nori kitokios ikonos nei webhook avataras
        run: python rss_to_webhook.py

      - name: Commit state.json
        run: |
          if [ -f state.json ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add state.json
            git commit -m "Update RSS state" || echo "No changes"
            git push || echo "No push"
          fi
