name: RSS -> Discord Webhook (DayZ)

permissions:
  contents: write

on:
  schedule:
    - cron: "*/20 * * * *"   # kas 20 min
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RSS_URL: "https://techcrunch.com/feed"
          WEBHOOK_NAME: "Būrio Ryšininkas"
          AVATAR_URL: ""
          MAX_POSTS: "3"
          POST_ON_FIRST_RUN: "1"
          AUTHOR_NAME: "Būrio Ryšininkas"
          FOOTER_TEXT: "Kareivių Nuotykiai • DayZ naujienos"
          EMBED_COLOR: "15158332" # raudona (discord red)
          THUMBNAIL_URL: "https://cdn.discordapp.com/attachments/1458072008146288721/1458974934717038836/0911ce6d90b2a0680494fc764ac38401.png?ex=696197ca&is=6960464a&hm=c161279d9d7e2375ee96ac6f7f55bb3fb74ad430938ad9c5d2d31847550bb734&"       # jei turi DayZ logo URL, įklijuok čia
          AUTHOR_ICON_URL: ""     # jei nori kitokios ikonos nei webhook avataras
        run: python rss_to_webhook.py

      - name: Commit state.json
        run: |
          if [ -f state.json ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add state.json
            git commit -m "Update RSS state" || echo "No changes"
            git push || echo "No push"
          fi
